lab7.12

diff --git a/.github/workflows/build-and-delivery.yml b/.github/workflows/build-and-delivery.yml
--- a/.github/workflows/build-and-delivery.yml
+++ b/.github/workflows/build-and-delivery.yml
@@ -17,7 +17,14 @@ jobs:
       with:
         username: ${{ vars.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
-    
+        
+    - name: List files
+      run: |
+        echo "Current dir: $(pwd)"
+        ls -la
+        echo "Dockerfile content:"
+        cat Dockerfile || echo "Dockerfile not found"
+
     - name: Build and push Docker image
       uses: docker/build-push-action@v6
       with:
